### ISSUE TITLE
jar does not contain resilience4j dependency

### ISSUE THREAD

**Issue by josephnatale** [aterleto/jedis#9]
might be by design but I had to add the maven-assembly-plugin to create a jar that contained the resilience4j dependencies, without this I needed to add 2 dependencies to get this to work, jedis and resillience4j

Please forgive my decaying Maven skills...there's a 99% chance I'm just building wrong....

**Comment by aterleto** [comment]
Hi Joe, you are correct. The resillience4j dependencies are _optional_ within the jedis maven project since this capability is only used by configuration for a single type of Redis connection. In other words, we didn't want to make it too heavy for all the other users. 

Below is a link explaining the purpose for optional dependencies. Although it seems you already found the way to make it work, if its too much of a burden on your application please do let us know. 

https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by josephnatale** [comment]
All good, makes sense.  Not everyone will be using the capability so we don't want to include the jar if you aren't using it.
